[platformio]
default_envs = teensy41

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

build_flags = 
    -Iinclude
    -Ilib/drivers
    -Ilib/drivers/dev
    -Ilib/bus
