[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200
build_flags = 
    -D ARDUINO_TEENSY41
    -I include
    -I src
    -D AHRS_DEBUG
; optional but helpful for cross-lib includes
lib_ldf_mode = chain+